### ISSUE TITLE
ModuleNotFoundError: No module named 'geolib.inits'

### ISSUE THREAD

**Issue by shaoeric** [likenneth/mmgnn_textvqa#2]
It is a very awesome work, but when i run the code, some troubles raised.  i find there is no inits.py in geolib, so i wonder how i can install a correct version of geolib

`Traceback (most recent call last):
  File "tools/run.py", line 100, in <module>
    run()
  File "tools/run.py", line 81, in run
    setup_imports()
  File "tools/run.py", line 61, in setup_imports
    importlib.import_module("pythia.models." + module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/lc/mmgnn-textvqa/pythia/models/s_mmgnn.py", line 8, in <module>
    from pythia.modules.si_module import SI_GNN
  File "/data/lc/mmgnn-textvqa/pythia/modules/si_module.py", line 7, in <module>
    from geolib.inits import glorot
ModuleNotFoundError: No module named 'geolib.inits'
`

**Comment by shaoeric** [comment]
i have found that in the history commit, thanks a lot

**Comment by georg3tom** [comment]
@shaoeric can you share the link to the commit

**Comment by shaoeric** [comment]
> @shaoeric can you share the link to the commit

[https://github.com/ricolike/mmgnn_textvqa/tree/b06a8fb2c676f1bfbd0b0da681e7aa9d36792344/geolib](https://github.com/ricolike/mmgnn_textvqa/tree/b06a8fb2c676f1bfbd0b0da681e7aa9d36792344/geolib)

**Comment by Alexandmrwh** [comment]
Sorry to bother you. Did you meet with this problem of missing data "pythia/../data/open_images/detectron_fix_100/fc6/train/b47a6f88ba073095.npy"? I think this should be the pre-trained image feature. But I didn't find where to download it. Thank you for your help!
